---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: compile_Python3_RedHat.yml
  when: ansible_os_family == 'RedHat'

- debug: msg="{{ compiled_python3_redhat_deps }}"
  when: ansible_os_family == 'RedHat'

- include: compile_Python3_Debian.yml
  when: ansible_os_family == 'Debian'
